language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
# command to install dependencies
install:
  - "pip install -r demo_project/requirements.txt"
  - "pip install --upgrade pip"
# command to run tests
script: cd demo_project && python manage.py test graphos demo --settings=demo_project.settings.test
services:
  - mongodb
